# Generated by Django 6.1 on 2026-09-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_triptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('custom', 'Custom')], default='equal', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='triptask',
            name='category',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('work', 'Work'), ('team', 'Team')], default='team', max_length=10),
        ),
        migrations.AddField(
            model_name='triptask',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
