# Generated by Django 6.1 on 2026-09-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expense_split_type_trip_status_triptask_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
